from social_core.exceptions import AuthAlreadyAssociated

class SocialAuthAlreadyAssociated(AuthAlreadyAssociated):
    """Custom exception for already associated social accounts."""